<a href="https://colab.research.google.com/github/iimahdii/Yield-stability-analysis/blob/main/StabilityV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:
import os.path
import numpy as  np

In [3]:
from pathlib import Path
input = Path ("/content/drive/MyDrive/dataset/histograms/histogram_veg.npz")
a = np.load(input)
for k in a.files:
    print (k)

output_image
output_yield
output_year
output_locations
output_index


In [4]:
# load data to memory
content   = np.load(input)
images    = content['output_image']
yields    = content['output_yield']
years     = content['output_year']
locations = content['output_locations']
indices   = content['output_index']

#NDVI Calculation

In [5]:
image_NDVI = np.zeros([images.shape[0],32,32])
for i in range(images.shape[0]):
  image_NDVI[i,:,:] = (images[i,4,:,:]-images[i,5,:,:])/(images[i,4,:,:]+images[i,5,:,:]+ np.finfo(float).eps)

#Stability Calculation

In [6]:
import numpy as np
def calculate_ndvi_bar(ndvi_data):
    """Calculate average NDVI for each year for jth polygon."""
    return np.mean(ndvi_data, axis=2)
def calculate_rndvi_and_snndvi(ndvi_data, ndvi_bar):
    """Calculate rNDVI and snNDVI for each pixel."""
    rNDVI = ndvi_data - ndvi_bar[:,:,np.newaxis]
    snNDVI = np.where(ndvi_data >= ndvi_bar[:,:,np.newaxis], 1, 0)
    return rNDVI, snNDVI

def calculate_snndvi_bar(snNDVI_data):
    """Calculate average snNDVI over years for each pixel."""
    return np.mean(snNDVI_data, axis=0)

def calculate_tnndvi(snNDVI_data, snNDVI_bar):
    """Calculate tnNDVI for each pixel."""
    diff = snNDVI_data - snNDVI_bar
    return np.sqrt(np.mean(diff**2, axis=0))

def classify_stability(ndvi_data, ndvi_bar, tnNDVI):
    """Classify each pixel into stability classes."""
    conditions = [
        (ndvi_data >= ndvi_bar[:,:,np.newaxis]) & (tnNDVI < 0.15),
        (ndvi_data >= ndvi_bar[:,:,np.newaxis]) & (tnNDVI > 0.15),
        (tnNDVI >= 0.15)
    ]
    #choices = ["SH", "SL", "U"]
    choices = [2, 1, 0]
    return np.select(conditions, choices)

# Input data (as an example)
# Assuming ndvi_data shape is (years, polygons, pixels)
# For this example, I'm creating random NDVI values for 8 years, 5 polygons, and 100 pixels.
ndvi_data = image_NDVI

# Step 1: Calculate NDVI bar
ndvi_bar = calculate_ndvi_bar(image_NDVI)

# Step 2: Calculate rNDVI and snNDVI
rNDVI, snNDVI = calculate_rndvi_and_snndvi(image_NDVI, ndvi_bar)

# Step 3: Calculate snNDVI bar and tnNDVI
snNDVI_bar = calculate_snndvi_bar(snNDVI)
tnNDVI = calculate_tnndvi(snNDVI, snNDVI_bar)

# Step 4: Classify stability
stability = classify_stability(image_NDVI, ndvi_bar, tnNDVI)

print(stability)

[[[0 0 0 ... 0 0 0]
  [1 1 1 ... 1 1 1]
  [0 0 0 ... 0 0 0]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[0 0 0 ... 1 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [1 1 1 ... 1 1 1]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 1 1 0]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  ...
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[0 0 0 ... 1 1 0]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  ...
  [0 0 0 ... 1 0 1]
  [1 1 1 ... 1 1 1]
  [1 1 1 ... 1 1 1]]

 [[1 1 0 ... 1 1 0]
  [1 1 1 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [1 1 1 ... 1 1 0]]]


In [7]:
savedir  = Path("/content/drive/MyDrive/stability/")
path = savedir /'result_prediction.npz'
np.savez(path, pred_out=stability,
         year_out=years,locations_out=locations,index_out=indices)

In [8]:
from bs4 import BeautifulSoup

In [27]:
max_values = {key: max(values) for key, values in LSTM.items()}
print(max_values)

{'01047': 2, '01051': 2, '01105': 2, '01119': 2, '01003': 2, '01009': 2, '01019': 2, '01043': 2, '01049': 2, '01071': 2, '01095': 2, '01033': 2, '01059': 2, '01077': 2, '01079': 2, '01083': 2, '01089': 2, '01057': 2, '01121': 2, '01125': 2, '01127': 2, '01069': 2, '05029': 2, '05045': 2, '05119': 2, '05001': 2, '05037': 2, '05077': 2, '05095': 2, '05107': 2, '05117': 2, '05123': 2, '05147': 2, '05021': 2, '05031': 2, '05055': 2, '05067': 2, '05075': 2, '05093': 2, '05111': 2, '05003': 2, '05017': 2, '05041': 2, '05043': 2, '05069': 2, '05079': 2, '10001': 2, '10003': 2, '10005': 2, '13225': 2, '13107': 2, '13163': 2, '13165': 2, '13147': 2, '13221': 2, '13055': 2, '13071': 2, '13177': 2, '13205': 2, '13243': 2, '13253': 2, '13275': 2, '17039': 2, '17107': 2, '17115': 2, '17123': 2, '17113': 2, '17129': 2, '17143': 2, '17179': 2, '17203': 2, '17019': 2, '17053': 2, '17075': 2, '17091': 2, '17105': 2, '17147': 2, '17183': 2, '17023': 2, '17025': 2, '17029': 2, '17033': 2, '17035': 2, '17

In [31]:

LSTM = {}
pred_year = 2018
savedir  = Path("/content/drive/MyDrive/stability/")
path_current = savedir/'result_prediction.npz'
data = np.load(path_current)

year1 = data['year_out']
pred1 = data['pred_out']
index1 = data['index_out']
locations1 = data['locations_out']

validate = np.nonzero(year1 == 2018)[0]
year = year1[validate]
pred = pred1[validate]
index = index1[validate]
locations = locations1[validate]

err_LSTM = pred
for i in range(pred.shape[0]):
    for j in range(pred.shape[1]):
        for k in range(pred.shape[2]):
            loc1 = str(int(index[i,0]))
            loc2 = str(int(index[i,1]))
            if len(loc1)==1:
                loc1='0'+loc1
            if len(loc2)==1:
                loc2='00'+loc2
            if len(loc2)==2:
                loc2='0'+loc2
            fips = loc1+loc2
            if fips in LSTM:
                LSTM[fips].append(err_LSTM[i, j, k])
            else:
                LSTM[fips] = [err_LSTM[i, j, k]]


'''LSTM'''
# Load the SVG map
svg = open('counties.svg', 'r').read()
# Load into Beautiful Soup
soup = BeautifulSoup(svg, 'xml')
# Find counties
paths = soup.findAll('path')
colors = ["#2166ac", "#20c937", "#b2182b"]
path_style = 'font-size:12px;fill-rule:nonzero;stroke:#FFFFFF;stroke-opacity:1;stroke-width:0.1;stroke-miterlimit:4;stroke-dasharray:none;stroke-linecap:butt;marker-start:none;stroke-linejoin:bevel;fill:'

for p in paths:
    if p['id'] not in ["State_Lines", "separator"]:
        try:
            rates = LSTM[p['id']]
            rate = np.mean(rates)
            #print(rate)
        except:
            continue
        if rate >= 0.52:
            color_class = 2
        elif 0.46 < rate < 0.52:
            color_class = 1
        else:
            color_class = 0

        color = colors[color_class]
        p['style'] = path_style + color

soup = soup.prettify()
with open('County.svg', 'wb') as f:
    f.write(soup.encode())